= Storing Files in Database

// todo Explain how to upload/download files in REST when https://github.com/Haulmont/jmix-core/issues/200 is fixed

The most common use case of storing files in the database is using entity fields of the byte array type.

CAUTION: Save only small files in the database: thumbnails, icons, etc., because the whole file is placed in memory when it is uploaded or downloaded.

Suppose you want to store small avatars for the `Person` entity. Firstly, create an attribute of the byte array (`byte[]`) type in your entity, for example:

[source,java,indent=0]
----
include::example$/ex1/src/main/java/files/ex1/entity/Person.java[tags=file]
----

When you run the application, Studio generates a database migration script for creating a corresponding column of the type appropriate for your database. For example, for PostgreSQL it is `bytea`.

Now you can use the xref:ui:vcl/components/file-upload-field.adoc[] component bound to the `photo` attribute to upload the file from a user interface, and the `Downloader` bean to download the file from UI or a service. If you create an editor screen with Studio, the `FileUploadField` will be added to your screen automatically.

See the next sections of this documentation for more details.
